# For advanced use and comprehensive documentation of the format, please see:
# http://docs.haskellstack.org/en/stable/yaml_configuration/

resolver: lts-14.19

packages:
  - '.'

#extra-deps: []
#flags: {}
